name       : haskell-tagged
version    : 0.8.5
release    : 1
source     :
    - https://hackage.haskell.org/package/tagged-0.8.5/tagged-0.8.5.tar.gz : e47c51c955ed77b0fa36897f652df990aa0a8c4eb278efaddcd604be00fc8d99
license    : BSD-3-Clause
component  : programming
summary    : Haskell 98 phantom types to avoid unsafely passing dummy arguments
description: |
    Haskell 98 phantom types to avoid unsafely passing dummy arguments
builddeps  :
    - ghc
    - haskell-transformers-compat
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 tagged-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/tagged-$version.conf
