name       : haskell-tagged
version    : 0.8.6
release    : 6
source     :
    - https://hackage.haskell.org/package/tagged-0.8.6/tagged-0.8.6.tar.gz : ad16def0884cf6f05ae1ae8e90192cf9d8d9673fa264b249499bd9e4fac791dd
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell 98 phantom types to avoid unsafely passing dummy arguments
description: |
    Haskell 98 phantom types to avoid unsafely passing dummy arguments
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    # sed -i "s|2.12|2.14|g" tagged.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
