name       : haskell-tagged
version    : 0.8.5
release    : 2
source     :
    - https://hackage.haskell.org/package/tagged-0.8.5/tagged-0.8.5.tar.gz : e47c51c955ed77b0fa36897f652df990aa0a8c4eb278efaddcd604be00fc8d99
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell 98 phantom types to avoid unsafely passing dummy arguments
description: |
    Haskell 98 phantom types to avoid unsafely passing dummy arguments
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-transformers-compat-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
